FROM node:20-alpine

WORKDIR /app

# Copy only package files first (better caching)
COPY package.json package-lock.json ./

# Copy workspace packages
COPY apps ./apps
COPY packages ./packages

RUN npm install

WORKDIR /app/apps/server

EXPOSE 3000

CMD ["npm", "run", "dev"]